import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../domain/entities/food_offer.dart';

// TODO(browse): Implémenter avec le vrai repository
/// Provider pour obtenir toutes les offres disponibles
final allOffersProvider = FutureProvider<List<FoodOffer>>((ref) async {
  await Future<void>.delayed(const Duration(seconds: 1));
  
  final now = DateTime.now();
  
  // Données simulées pour le développement
  return [
    FoodOffer(
      id: 'browse1',
      title: 'Salade composée du jour',
      merchantName: 'Healthy Corner',
      merchantId: 'merchant1',
      description: 'Salade fraîche avec légumes de saison',
      originalPrice: 12,
      discountedPrice: 5.50,
      pickupStartTime: now.add(const Duration(hours: 2)),
      pickupEndTime: now.add(const Duration(hours: 3)),
      quantity: 8,
      images: const ['https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=800'],
      category: FoodCategory.dejeuner,
      type: OfferType.plat,
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8566,
        longitude: 2.3522,
        address: '15 Rue de la Santé',
        city: 'Paris',
        postalCode: '75013',
      ),
      isVegetarian: true,
      availableQuantity: 8,
      merchantAddress: '15 Rue de la Santé, 75013 Paris',
      tags: const ['Healthy', 'Végétarien'],
      createdAt: now.subtract(const Duration(hours: 3)),
      updatedAt: now.subtract(const Duration(hours: 1)),
      rating: 4.8,
      distanceKm: 0.8,
    ),
    FoodOffer(
      id: 'browse2',
      title: 'Box sushi variés',
      merchantName: 'Tokyo Express',
      merchantId: 'merchant2',
      description: 'Assortiment de 12 sushis et makis',
      originalPrice: 24,
      discountedPrice: 12,
      pickupStartTime: now.add(const Duration(minutes: 45)),
      pickupEndTime: now.add(const Duration(hours: 2)),
      quantity: 6,
      images: const ['https://images.unsplash.com/photo-1553621042-f6e147245754?w=800'],
      category: FoodCategory.diner,
      type: OfferType.plat,
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8584,
        longitude: 2.2945,
        address: '89 Avenue Kléber',
        city: 'Paris',
        postalCode: '75016',
      ),
      allergens: const ['Poisson', 'Soja'],
      availableQuantity: 3,
      merchantAddress: '89 Avenue Kléber, 75016 Paris',
      tags: const ['Japonais', 'Sushi'],
      createdAt: now.subtract(const Duration(hours: 2)),
      updatedAt: now.subtract(const Duration(minutes: 30)),
      rating: 4.6,
      distanceKm: 1.2,
    ),
    FoodOffer(
      id: 'browse3',
      title: 'Pâtisseries du jour',
      merchantName: 'La Petite Boulangerie',
      merchantId: 'merchant3',
      description: 'Assortiment de pâtisseries artisanales',
      originalPrice: 15,
      discountedPrice: 6,
      pickupStartTime: now.add(const Duration(hours: 3)),
      pickupEndTime: now.add(const Duration(hours: 4)),
      quantity: 10,
      images: const ['https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800'],
      category: FoodCategory.dessert,
      type: OfferType.boulangerie,
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8530,
        longitude: 2.3499,
        address: '42 Rue du Bac',
        city: 'Paris',
        postalCode: '75007',
      ),
      allergens: const ['Gluten', 'Lactose', 'Œufs'],
      isVegetarian: true,
      availableQuantity: 7,
      merchantAddress: '42 Rue du Bac, 75007 Paris',
      tags: const ['Artisanal', 'Pâtisserie'],
      createdAt: now.subtract(const Duration(hours: 4)),
      updatedAt: now.subtract(const Duration(hours: 2)),
      rating: 4.9,
      distanceKm: 0.5,
    ),
    FoodOffer(
      id: 'browse4',
      title: 'Plat du jour GRATUIT',
      merchantName: 'Resto Solidaire',
      merchantId: 'merchant4',
      description: 'Plat complet offert par notre restaurant solidaire',
      originalPrice: 0,
      discountedPrice: 0,
      pickupStartTime: now.add(const Duration(hours: 1)),
      pickupEndTime: now.add(const Duration(hours: 2)),
      quantity: 20,
      images: const ['https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800'],
      category: FoodCategory.dejeuner,
      type: OfferType.plat,
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8682,
        longitude: 2.3548,
        address: '123 Rue de Belleville',
        city: 'Paris',
        postalCode: '75020',
      ),
      isVegetarian: true,
      isHalal: true,
      availableQuantity: 20,
      merchantAddress: '123 Rue de Belleville, 75020 Paris',
      tags: const ['Gratuit', 'Solidaire', 'Halal'],
      createdAt: now.subtract(const Duration(hours: 1)),
      updatedAt: now,
      rating: 5,
      distanceKm: 2.1,
    ),
    FoodOffer(
      id: 'browse5',
      title: 'Panier de légumes bio',
      merchantName: 'Bio Market',
      merchantId: 'merchant5',
      description: 'Légumes frais bio de producteurs locaux',
      originalPrice: 25,
      discountedPrice: 10,
      pickupStartTime: now.add(const Duration(hours: 1)),
      pickupEndTime: now.add(const Duration(hours: 3)),
      quantity: 15,
      images: const ['https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800'],
      category: FoodCategory.fruitLegume,
      type: OfferType.fruits,
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8461,
        longitude: 2.3712,
        address: '67 Boulevard Voltaire',
        city: 'Paris',
        postalCode: '75011',
      ),
      isVegetarian: true,
      isVegan: true,
      availableQuantity: 10,
      merchantAddress: '67 Boulevard Voltaire, 75011 Paris',
      tags: const ['Bio', 'Local', 'Vegan'],
      createdAt: now.subtract(const Duration(hours: 2)),
      updatedAt: now.subtract(const Duration(hours: 1)),
      rating: 4.7,
      distanceKm: 1.5,
    ),
  ];
});