import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/brand.dart';

/// Provider pour récupérer toutes les marques/enseignes
final brandsProvider = FutureProvider<List<Brand>>((ref) async {
  // TODO: Implémenter le service des marques
  // Pour l'instant, retourner des données de test
  await Future.delayed(const Duration(milliseconds: 500)); // Simuler un appel réseau
  
  return [
    Brand(
      id: '1',
      name: 'Carrefour',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/thumb/3/3b/Logo_Carrefour.svg/1200px-Logo_Carrefour.svg.png',
      category: 'Supermarché',
      totalStores: 1200,
      activeOffers: 45,
      averageDiscount: 35.0,
      description: 'Grande enseigne de distribution',
      primaryColor: '#0066CC',
      isPremium: true,
    ),
    Brand(
      id: '2',
      name: 'McDonald\'s',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/McDonald%27s_Golden_Arches.svg/1200px-McDonald%27s_Golden_Arches.svg.png',
      category: 'Restaurant',
      totalStores: 1400,
      activeOffers: 52,
      averageDiscount: 30.0,
      description: 'Fast food international',
      primaryColor: '#FFC72C',
      backgroundColor: '#DA291C',
      isPremium: true,
    ),
    Brand(
      id: '3',
      name: 'Starbucks',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d3/Starbucks_Corporation_Logo_2011.svg/1200px-Starbucks_Corporation_Logo_2011.svg.png',
      category: 'Café',
      totalStores: 450,
      activeOffers: 38,
      averageDiscount: 25.0,
      description: 'Coffee shop premium',
      primaryColor: '#00704A',
      isNew: true,
    ),
    Brand(
      id: '4',
      name: 'Paul',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/thumb/0/05/Logo_Paul_2019.png/1200px-Logo_Paul_2019.png',
      category: 'Boulangerie',
      totalStores: 750,
      activeOffers: 42,
      averageDiscount: 40.0,
      description: 'Boulangerie française traditionnelle',
      primaryColor: '#8B4513',
    ),
    Brand(
      id: '5',
      name: 'Monoprix',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/thumb/7/7a/Logo_Monoprix_2014.svg/1200px-Logo_Monoprix_2014.svg.png',
      category: 'Supermarché',
      totalStores: 800,
      activeOffers: 32,
      averageDiscount: 28.0,
      description: 'Supermarché urbain',
      primaryColor: '#FF6B35',
    ),
    Brand(
      id: '6',
      name: 'Picard',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/thumb/f/f9/Logo_Picard_Surgelés_2019.svg/1200px-Logo_Picard_Surgelés_2019.svg.png',
      category: 'Surgelés',
      totalStores: 1000,
      activeOffers: 28,
      averageDiscount: 50.0,
      description: 'Spécialiste des surgelés',
      primaryColor: '#00A651',
      isPremium: true,
    ),
    Brand(
      id: '7',
      name: 'Burger King',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Burger_King_logo_%281999%29.svg/1200px-Burger_King_logo_%281999%29.svg.png',
      category: 'Restaurant',
      totalStores: 450,
      activeOffers: 35,
      averageDiscount: 45.0,
      description: 'Home of the Whopper',
      primaryColor: '#EC1C24',
      backgroundColor: '#FDBD2D',
    ),
    Brand(
      id: '8',
      name: 'Subway',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Subway_2016_logo.svg/1200px-Subway_2016_logo.svg.png',
      category: 'Restaurant',
      totalStores: 850,
      activeOffers: 40,
      averageDiscount: 35.0,
      description: 'Sandwiches frais',
      primaryColor: '#00A650',
      backgroundColor: '#FFC600',
      isNew: true,
    ),
    Brand(
      id: '9',
      name: 'Franprix',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/fr/thumb/8/86/Logo_Franprix_2015.svg/1200px-Logo_Franprix_2015.svg.png',
      category: 'Supermarché',
      totalStores: 600,
      activeOffers: 28,
      averageDiscount: 22.0,
      description: 'Proximité et qualité',
      primaryColor: '#2E8B57',
    ),
    Brand(
      id: '10',
      name: 'KFC',
      logoUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/b/bf/KFC_logo.svg/1200px-KFC_logo.svg.png',
      category: 'Restaurant',
      totalStores: 260,
      activeOffers: 25,
      averageDiscount: 40.0,
      description: 'Poulet frit Kentucky',
      primaryColor: '#C8102E',
      isNew: true,
    ),
  ];
});
