import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/brand.dart';

/// Provider pour récupérer toutes les marques/enseignes
final brandsProvider = FutureProvider<List<Brand>>((ref) async {
  // TODO: Implémenter le service des marques
  // Pour l'instant, retourner des données de test
  await Future<void>.delayed(const Duration(milliseconds: 500)); // Simuler un appel réseau
  
  return [
    const Brand(
      id: '1',
      name: 'Carrefour',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2020/09/Carrefour-Logo.png',
      category: 'Supermarché',
      totalStores: 1200,
      activeOffers: 45,
      averageDiscount: 35,
      description: 'Grande enseigne de distribution',
      primaryColor: '#0066CC',
      isPremium: true,
    ),
    const Brand(
      id: '2',
      name: "McDonald's",
      logoUrl: 'https://1000logos.net/wp-content/uploads/2017/03/McDonalds-logo.png',
      category: 'Restaurant',
      totalStores: 1400,
      activeOffers: 52,
      averageDiscount: 30,
      description: 'Fast food international',
      primaryColor: '#FFC72C',
      backgroundColor: '#DA291C',
      isPremium: true,
    ),
    const Brand(
      id: '3',
      name: 'Starbucks',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2017/03/Stabucks-Logo.png',
      category: 'Café',
      totalStores: 450,
      activeOffers: 38,
      averageDiscount: 25,
      description: 'Coffee shop premium',
      primaryColor: '#00704A',
      isNew: true,
    ),
    const Brand(
      id: '4',
      name: 'Paul',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2021/04/Paul-logo.png',
      category: 'Boulangerie',
      totalStores: 750,
      activeOffers: 42,
      averageDiscount: 40,
      description: 'Boulangerie française traditionnelle',
      primaryColor: '#8B4513',
    ),
    const Brand(
      id: '5',
      name: 'Monoprix',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2020/09/Monoprix-Logo.png',
      category: 'Supermarché',
      totalStores: 800,
      activeOffers: 32,
      averageDiscount: 28,
      description: 'Supermarché urbain',
      primaryColor: '#FF6B35',
    ),
    const Brand(
      id: '6',
      name: 'Picard',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2021/04/Picard-logo.png',
      category: 'Surgelés',
      totalStores: 1000,
      activeOffers: 28,
      averageDiscount: 50,
      description: 'Spécialiste des surgelés',
      primaryColor: '#00A651',
      isPremium: true,
    ),
    const Brand(
      id: '7',
      name: 'Burger King',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2017/03/Burger-King-logo.png',
      category: 'Restaurant',
      totalStores: 450,
      activeOffers: 35,
      averageDiscount: 45,
      description: 'Home of the Whopper',
      primaryColor: '#EC1C24',
      backgroundColor: '#FDBD2D',
    ),
    const Brand(
      id: '8',
      name: 'Subway',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2017/03/Subway-logo.png',
      category: 'Restaurant',
      totalStores: 850,
      activeOffers: 40,
      averageDiscount: 35,
      description: 'Sandwiches frais',
      primaryColor: '#00A650',
      backgroundColor: '#FFC600',
      isNew: true,
    ),
    const Brand(
      id: '9',
      name: 'Franprix',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2020/09/Franprix-Logo.png',
      category: 'Supermarché',
      totalStores: 600,
      activeOffers: 28,
      averageDiscount: 22,
      description: 'Proximité et qualité',
      primaryColor: '#2E8B57',
    ),
    const Brand(
      id: '10',
      name: 'KFC',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2017/03/KFC-Logo.png',
      category: 'Restaurant',
      totalStores: 260,
      activeOffers: 25,
      averageDiscount: 40,
      description: 'Poulet frit Kentucky',
      primaryColor: '#C8102E',
      isNew: true,
    ),
    const Brand(
      id: '11',
      name: 'Auchan',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2020/09/Auchan-Logo.png',
      category: 'Supermarché',
      totalStores: 1800,
      activeOffers: 55,
      averageDiscount: 32,
      description: 'Grande distribution française',
      primaryColor: '#005CA9',
    ),
    const Brand(
      id: '12',
      name: 'Leclerc',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2020/09/E-Leclerc-Logo.png',
      category: 'Supermarché',
      totalStores: 750,
      activeOffers: 48,
      averageDiscount: 30,
      description: 'Enseigne de grande distribution',
      primaryColor: '#005CA9',
    ),
    const Brand(
      id: '13',
      name: 'Intermarché',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2020/09/Intermarche-Logo.png',
      category: 'Supermarché',
      totalStores: 2000,
      activeOffers: 42,
      averageDiscount: 28,
      description: 'Réseau de supermarchés',
      primaryColor: '#ED1C24',
    ),
    const Brand(
      id: '14',
      name: 'Casino',
      logoUrl: 'https://1000logos.net/wp-content/uploads/2020/09/Casino-Logo.png',
      category: 'Supermarché',
      totalStores: 12000,
      activeOffers: 38,
      averageDiscount: 26,
      description: 'Groupe de distribution français',
      primaryColor: '#0066CC',
    ),
  ];
});
