import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/merchant.dart';

/// Provider pour la liste des marchands partenaires
final merchantsProvider = FutureProvider<List<Merchant>>((ref) async {
  // Simuler un appel API
  await Future.delayed(const Duration(milliseconds: 500));
  
  // Données mockées de marchands
  return [
    Merchant(
      id: 'm1',
      name: 'Boulangerie Paul',
      category: 'Boulangerie',
      cuisineType: 'Viennoiseries & Sandwichs',
      imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
      rating: 4.8,
      distanceText: '0.5 km',
      availableOffers: 4,
      hasActiveOffer: true,
      originalPrice: 12.00,
      discountedPrice: 4.99,
      discountPercentage: 58,
      minPrice: 3.99,
      pickupTime: '18:00 - 19:00',
      isFavorite: true,
      tags: ['Bio', 'Local', '⚡ Rapide'],
    ),
    Merchant(
      id: 'm2',
      name: 'Sushi Shop',
      category: 'Japonais',
      cuisineType: 'Sushis & Makis',
      imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=400',
      rating: 4.6,
      distanceText: '1.2 km',
      availableOffers: 2,
      hasActiveOffer: true,
      originalPrice: 25.00,
      discountedPrice: 9.99,
      discountPercentage: 60,
      minPrice: 8.99,
      pickupTime: '19:30 - 20:00',
      isFavorite: false,
      tags: ['Premium', 'Halal'],
    ),
    Merchant(
      id: 'm3',
      name: 'Le Bistrot du Coin',
      category: 'Français',
      cuisineType: 'Cuisine traditionnelle',
      imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=400',
      rating: 4.5,
      distanceText: '800 m',
      availableOffers: 3,
      hasActiveOffer: true,
      originalPrice: 18.00,
      discountedPrice: 6.99,
      discountPercentage: 61,
      minPrice: 5.99,
      pickupTime: '21:00 - 21:30',
      isFavorite: false,
      tags: ['Terrasse', 'Wi-Fi'],
    ),
    Merchant(
      id: 'm4',
      name: 'Pizza Express',
      category: 'Italien',
      cuisineType: 'Pizzas & Pâtes',
      imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=400',
      rating: 4.3,
      distanceText: '2.1 km',
      availableOffers: 5,
      hasActiveOffer: true,
      originalPrice: 15.00,
      discountedPrice: 5.99,
      discountPercentage: 60,
      minPrice: 4.99,
      pickupTime: '20:30 - 21:00',
      isFavorite: true,
      tags: ['Livraison', 'Végétarien'],
    ),
    Merchant(
      id: 'm5',
      name: 'Green Bowl',
      category: 'Healthy',
      cuisineType: 'Salades & Bowls',
      imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=400',
      rating: 4.7,
      distanceText: '1.5 km',
      availableOffers: 3,
      hasActiveOffer: true,
      originalPrice: 14.00,
      discountedPrice: 5.50,
      discountPercentage: 61,
      minPrice: 4.50,
      pickupTime: '19:00 - 19:30',
      isFavorite: false,
      tags: ['Vegan', 'Sans gluten', 'Bio'],
    ),
    Merchant(
      id: 'm6',
      name: 'Café de la Gare',
      category: 'Café',
      cuisineType: 'Café & Pâtisseries',
      imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
      rating: 4.4,
      distanceText: '300 m',
      availableOffers: 2,
      hasActiveOffer: true,
      originalPrice: 8.00,
      discountedPrice: 2.99,
      discountPercentage: 63,
      minPrice: 2.50,
      pickupTime: '17:30 - 18:00',
      isFavorite: false,
      tags: ['☕ Café', 'Wi-Fi'],
    ),
    Merchant(
      id: 'm7',
      name: 'Traiteur Libanais',
      category: 'Oriental',
      cuisineType: 'Mezzés & Grillades',
      imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
      rating: 4.9,
      distanceText: '1.8 km',
      availableOffers: 6,
      hasActiveOffer: true,
      originalPrice: 22.00,
      discountedPrice: 8.99,
      discountPercentage: 59,
      minPrice: 7.99,
      pickupTime: '20:00 - 20:30',
      isFavorite: true,
      tags: ['Halal', 'Végétarien', 'Fait maison'],
    ),
    Merchant(
      id: 'm8',
      name: 'Fromagerie du Marché',
      category: 'Fromagerie',
      cuisineType: 'Fromages & Charcuterie',
      imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400',
      rating: 4.7,
      distanceText: '650 m',
      availableOffers: 3,
      hasActiveOffer: true,
      originalPrice: 16.00,
      discountedPrice: 6.50,
      discountPercentage: 59,
      minPrice: 5.50,
      pickupTime: '18:30 - 19:00',
      isFavorite: false,
      tags: ['Local', 'Artisanal'],
    ),
    Merchant(
      id: 'm9',
      name: 'Thai Express',
      category: 'Asiatique',
      cuisineType: 'Pad Thai & Currys',
      imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400',
      rating: 4.5,
      distanceText: '2.3 km',
      availableOffers: 4,
      hasActiveOffer: true,
      originalPrice: 19.00,
      discountedPrice: 7.50,
      discountPercentage: 61,
      minPrice: 6.50,
      pickupTime: '21:00 - 21:30',
      isFavorite: false,
      tags: ['🌶 Picé', 'Sans gluten disponible'],
    ),
    Merchant(
      id: 'm10',
      name: 'Burger Factory',
      category: 'Américain',
      cuisineType: 'Burgers & Frites',
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400',
      rating: 4.4,
      distanceText: '1.1 km',
      availableOffers: 5,
      hasActiveOffer: true,
      originalPrice: 17.00,
      discountedPrice: 6.99,
      discountPercentage: 59,
      minPrice: 5.99,
      pickupTime: '22:00 - 22:30',
      isFavorite: true,
      tags: ['Late night', '🍔 Burger'],
    ),
    Merchant(
      id: 'm11',
      name: 'Pâtisserie Royale',
      category: 'Pâtisserie',
      cuisineType: 'Gâteaux & Tartes',
      imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400',
      rating: 4.8,
      distanceText: '900 m',
      availableOffers: 2,
      hasActiveOffer: true,
      originalPrice: 20.00,
      discountedPrice: 7.99,
      discountPercentage: 60,
      minPrice: 6.99,
      pickupTime: '17:00 - 17:30',
      isFavorite: false,
      tags: ['Premium', 'Artisanal', '🍰 Desserts'],
    ),
    Merchant(
      id: 'm12',
      name: 'Kebab Palace',
      category: 'Turc',
      cuisineType: 'Kebabs & Wraps',
      imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=400',
      rating: 4.2,
      distanceText: '1.4 km',
      availableOffers: 7,
      hasActiveOffer: true,
      originalPrice: 12.00,
      discountedPrice: 4.50,
      discountPercentage: 63,
      minPrice: 3.99,
      pickupTime: '23:00 - 23:30',
      isFavorite: false,
      tags: ['Halal', 'Late night', 'Rapide'],
    ),
    Merchant(
      id: 'm13',
      name: 'Smoothie Bar',
      category: 'Jus & Smoothies',
      cuisineType: 'Boissons fraîches',
      imageUrl: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=400',
      rating: 4.6,
      distanceText: '400 m',
      availableOffers: 4,
      hasActiveOffer: true,
      originalPrice: 9.00,
      discountedPrice: 3.50,
      discountPercentage: 61,
      minPrice: 2.99,
      pickupTime: '16:00 - 16:30',
      isFavorite: true,
      tags: ['Healthy', 'Vegan', '🥤 Smoothies'],
    ),
    Merchant(
      id: 'm14',
      name: 'Crêperie Bretonne',
      category: 'Crêperie',
      cuisineType: 'Crêpes & Galettes',
      imageUrl: 'https://images.unsplash.com/photo-1519676867240-f03562e64548?w=400',
      rating: 4.7,
      distanceText: '1.6 km',
      availableOffers: 3,
      hasActiveOffer: true,
      originalPrice: 14.00,
      discountedPrice: 5.50,
      discountPercentage: 61,
      minPrice: 4.50,
      pickupTime: '19:00 - 19:30',
      isFavorite: false,
      tags: ['Traditionnel', 'Fait maison'],
    ),
    Merchant(
      id: 'm15',
      name: 'Poke Bowl Paradise',
      category: 'Hawaïen',
      cuisineType: 'Poke & Bowls',
      imageUrl: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=400',
      rating: 4.5,
      distanceText: '2.0 km',
      availableOffers: 4,
      hasActiveOffer: true,
      originalPrice: 18.00,
      discountedPrice: 7.99,
      discountPercentage: 56,
      minPrice: 6.99,
      pickupTime: '20:30 - 21:00',
      isFavorite: false,
      tags: ['Healthy', 'Sans gluten', '🌺 Exotique'],
    ),
  ];
});

/// Provider pour filtrer les marchands favoris
final favoriteMerchantsProvider = Provider<List<Merchant>>((ref) {
  final merchantsAsync = ref.watch(merchantsProvider);
  
  return merchantsAsync.when(
    data: (merchants) => merchants.where((m) => m.isFavorite).toList(),
    loading: () => [],
    error: (_, __) => [],
  );
});

