import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../domain/entities/food_offer.dart';

/// Provider pour les offres recommandées
final recommendedOffersProvider = FutureProvider<List<FoodOffer>>((ref) async {
  // Simuler un appel API
  await Future<void>.delayed(const Duration(milliseconds: 500));
  
  // Données mockées pour la démo
  final now = DateTime.now();
  return [
    FoodOffer(
      id: '1',
      merchantId: 'm1',
      merchantName: 'Boulangerie Paul',
      title: 'Panier Viennoiseries du jour',
      description: 'Assortiment de croissants, pains au chocolat et chaussons aux pommes',
      images: ['https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400'],
      type: OfferType.boulangerie,
      category: FoodCategory.boulangerie,
      originalPrice: 12.50,
      discountedPrice: 4.99,
      merchantAddress: '12 rue de la Boulangerie, 75001 Paris',
      quantity: 5,
      pickupStartTime: now.add(const Duration(hours: 1)),
      pickupEndTime: now.add(const Duration(hours: 3)),
      createdAt: now.subtract(const Duration(hours: 2)),
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8566,
        longitude: 2.3522,
        address: '15 rue du Commerce',
        city: 'Paris',
        postalCode: '75015',
      ),
      co2Saved: 750,
      updatedAt: now.subtract(const Duration(hours: 2)),
    ),
    FoodOffer(
      id: '2',
      merchantId: 'm2',
      merchantName: 'Carrefour Express',
      title: 'Panier Fruits & Légumes',
      description: 'Sélection de fruits et légumes du jour à consommer rapidement',
      images: ['https://images.unsplash.com/photo-1543168256-418811576931?w=400'],
      type: OfferType.fruits,
      category: FoodCategory.fruitLegume,
      originalPrice: 15,
      discountedPrice: 5,
      merchantAddress: '23 avenue de la République, 75011 Paris',
      quantity: 8,
      pickupStartTime: now.add(const Duration(hours: 2)),
      pickupEndTime: now.add(const Duration(hours: 4)),
      createdAt: now.subtract(const Duration(hours: 1)),
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8584,
        longitude: 2.3545,
        address: '23 avenue de la République',
        city: 'Paris',
        postalCode: '75011',
      ),
      isVegetarian: true,
      isVegan: true,
      co2Saved: 1200,
      updatedAt: now.subtract(const Duration(hours: 1)),
    ),
    FoodOffer(
      id: '3',
      merchantId: 'm3',
      merchantName: 'McDonalds',
      title: 'Menu Surprise du soir',
      description: 'Un menu complet avec burger, frites et boisson',
      images: ['https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=400'],
      type: OfferType.plat,
      category: FoodCategory.diner,
      originalPrice: 9.90,
      discountedPrice: 3.99,
      merchantAddress: '67 rue de la Paix, 75002 Paris',
      quantity: 12,
      pickupStartTime: now.add(const Duration(hours: 3)),
      pickupEndTime: now.add(const Duration(hours: 5)),
      createdAt: now.subtract(const Duration(minutes: 30)),
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8606,
        longitude: 2.3376,
        address: '140 avenue des Champs-Élysées',
        city: 'Paris',
        postalCode: '75008',
      ),
      allergens: ['gluten', 'lactose'],
      co2Saved: 600,
      updatedAt: now.subtract(const Duration(minutes: 30)),
    ),
    FoodOffer(
      id: '4',
      merchantId: 'm4',
      merchantName: 'Monoprix',
      title: 'Panier Anti-Gaspi du soir',
      description: 'Assortiment varié de produits à date courte',
      images: ['https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=400'],
      type: OfferType.panier,
      category: FoodCategory.autre,
      originalPrice: 20,
      discountedPrice: 6.99,
      merchantAddress: '89 boulevard Voltaire, 75011 Paris',
      quantity: 10,
      pickupStartTime: now.add(const Duration(hours: 2)),
      pickupEndTime: now.add(const Duration(hours: 4)),
      createdAt: now.subtract(const Duration(hours: 3)),
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8625,
        longitude: 2.3444,
        address: '52 rue de Rivoli',
        city: 'Paris',
        postalCode: '75004',
      ),
      co2Saved: 1500,
      updatedAt: now.subtract(const Duration(hours: 3)),
    ),
    FoodOffer(
      id: '5',
      merchantId: 'm5',
      merchantName: 'Starbucks',
      title: 'Goûter Gourmand',
      description: 'Pâtisseries et boissons chaudes de fin de journée',
      images: ['https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400'],
      type: OfferType.panier,
      category: FoodCategory.snack,
      originalPrice: 12,
      discountedPrice: 0, // Gratuit !
      merchantAddress: '5 place de la Bastille, 75011 Paris',
      quantity: 3,
      pickupStartTime: now.add(const Duration(hours: 1)),
      pickupEndTime: now.add(const Duration(hours: 2)),
      createdAt: now.subtract(const Duration(minutes: 45)),
      status: OfferStatus.available,
      location: const Location(
        latitude: 48.8530,
        longitude: 2.3499,
        address: '5 place de la Bastille',
        city: 'Paris',
        postalCode: '75011',
      ),
      isVegetarian: true,
      allergens: ['gluten', 'fruits à coque'],
      co2Saved: 400,
      updatedAt: now.subtract(const Duration(minutes: 45)),
    ),
  ];
});
