# This file configures the analyzer for EcoPlates project
# Uses very_good_analysis for enterprise-grade code quality

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    use_setters_to_change_properties: ignore
    prefer_int_literals: ignore
    non_constant_identifier_names: ignore
    prefer_const_constructors: ignore
    deprecated_member_use: error
    deprecated_member_use_from_same_package: error
   
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
    - "lib/generated/**"
    - "build/**"
    - "test/.test_coverage.dart"
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Personnalisations pour EcoPlates
    
    # Style & Formatting
    prefer_single_quotes: true
    prefer_relative_imports: true
    always_use_package_imports: false
    
    # Performance
    avoid_function_literals_in_foreach_calls: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Architecture Clean Code
    prefer_final_locals: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    
    # Enterprise specific
    public_member_api_docs: false  # Documentation optionnelle pour ce projet
    lines_longer_than_80_chars: false  # Autorisé pour les écrans modernes
    
    # Riverpod specific
    # avoid_manual_providers_as_generated_provider_dependency: true  # Règle non disponible
